// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "remoteSTAR_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// LogLikGLS_cpp
double LogLikGLS_cpp(double nugget, const MapMatd& X, const MapMatd& V, const MapMatd& y);
RcppExport SEXP _remoteSTAR_LogLikGLS_cpp(SEXP nuggetSEXP, SEXP XSEXP, SEXP VSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type nugget(nuggetSEXP);
    Rcpp::traits::input_parameter< const MapMatd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const MapMatd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const MapMatd& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(LogLikGLS_cpp(nugget, X, V, y));
    return rcpp_result_gen;
END_RCPP
}
// fitGLS_cpp
List fitGLS_cpp(const MapMatd& X, const MapMatd& V, const MapMatd& y, const MapMatd& X0, double nugget, bool save_xx, const int threads);
RcppExport SEXP _remoteSTAR_fitGLS_cpp(SEXP XSEXP, SEXP VSEXP, SEXP ySEXP, SEXP X0SEXP, SEXP nuggetSEXP, SEXP save_xxSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MapMatd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const MapMatd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const MapMatd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const MapMatd& >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< double >::type nugget(nuggetSEXP);
    Rcpp::traits::input_parameter< bool >::type save_xx(save_xxSEXP);
    Rcpp::traits::input_parameter< const int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fitGLS_cpp(X, V, y, X0, nugget, save_xx, threads));
    return rcpp_result_gen;
END_RCPP
}
// MatMult
MatrixXd MatMult(const MapMatd& A, const MapMatd& B, int cores);
RcppExport SEXP _remoteSTAR_MatMult(SEXP ASEXP, SEXP BSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MapMatd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const MapMatd& >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(MatMult(A, B, cores));
    return rcpp_result_gen;
END_RCPP
}
// AtA
MatrixXd AtA(const MatrixXd& A);
RcppExport SEXP _remoteSTAR_AtA(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(AtA(A));
    return rcpp_result_gen;
END_RCPP
}
// solve_cpp
MatrixXd solve_cpp(const MatrixXd& A, const MatrixXd& B);
RcppExport SEXP _remoteSTAR_solve_cpp(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const MatrixXd& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_cpp(A, B));
    return rcpp_result_gen;
END_RCPP
}
// solve_ident_cpp
MatrixXd solve_ident_cpp(const MatrixXd& A);
RcppExport SEXP _remoteSTAR_solve_ident_cpp(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(solve_ident_cpp(A));
    return rcpp_result_gen;
END_RCPP
}
// invchol_cpp
MatrixXd invchol_cpp(const MapMatd& V, double nugget);
RcppExport SEXP _remoteSTAR_invchol_cpp(SEXP VSEXP, SEXP nuggetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MapMatd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type nugget(nuggetSEXP);
    rcpp_result_gen = Rcpp::wrap(invchol_cpp(V, nugget));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_remoteSTAR_LogLikGLS_cpp", (DL_FUNC) &_remoteSTAR_LogLikGLS_cpp, 4},
    {"_remoteSTAR_fitGLS_cpp", (DL_FUNC) &_remoteSTAR_fitGLS_cpp, 7},
    {"_remoteSTAR_MatMult", (DL_FUNC) &_remoteSTAR_MatMult, 3},
    {"_remoteSTAR_AtA", (DL_FUNC) &_remoteSTAR_AtA, 1},
    {"_remoteSTAR_solve_cpp", (DL_FUNC) &_remoteSTAR_solve_cpp, 2},
    {"_remoteSTAR_solve_ident_cpp", (DL_FUNC) &_remoteSTAR_solve_ident_cpp, 1},
    {"_remoteSTAR_invchol_cpp", (DL_FUNC) &_remoteSTAR_invchol_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_remoteSTAR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
