# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AtA <- function(A) {
    .Call('_remoteSTAR_AtA', PACKAGE = 'remoteSTAR', A)
}

tinvchol_cpp <- function(V, nugget = 0.) {
    .Call('_remoteSTAR_tinvchol_cpp', PACKAGE = 'remoteSTAR', V, nugget)
}

fitGLS_cpp <- function(X, V, y, X0, nugget = 0., save_xx = FALSE, threads = 1L) {
    .Call('_remoteSTAR_fitGLS_cpp', PACKAGE = 'remoteSTAR', X, V, y, X0, nugget, save_xx, threads)
}

LogLikGLS_cpp <- function(nugget, X, V, y) {
    .Call('_remoteSTAR_LogLikGLS_cpp', PACKAGE = 'remoteSTAR', nugget, X, V, y)
}

optimizeNugget_cpp <- function(X, V, y, lower = 0, upper = 1, tol = .00001, debug = FALSE) {
    .Call('_remoteSTAR_optimizeNugget_cpp', PACKAGE = 'remoteSTAR', X, V, y, lower, upper, tol, debug)
}

GLS_worker_cpp <- function(y, X, V, X0, save_xx = FALSE) {
    .Call('_remoteSTAR_GLS_worker_cpp', PACKAGE = 'remoteSTAR', y, X, V, X0, save_xx)
}

crosspart_worker_cpp <- function(Li, Lj, Vij, df1, df2) {
    .Call('_remoteSTAR_crosspart_worker_cpp', PACKAGE = 'remoteSTAR', Li, Lj, Vij, df1, df2)
}

